import os


def _to_tex_safe_token(token):
    """Convert token to LaTeX-safe string.

    Parameters:
        token (str): Input token.

    Returns:
        str: Escaped token.
    """
    if token == "</s>":
        return "\\textless/s\\textgreater"
    return token


def export_latex_macros(results, macro_path):
    """Export key numeric outputs as LaTeX macros.

    Parameters:
        results (dict): Aggregated result payload.
        macro_path (str): Target path for macro file.

    Returns:
        None.
    """
    q1_pad = results["q1"]["padding_and_indexing"]
    q1_decode = results["q1"]["decoding"]
    q1_bleu = results["q1"]["bleu"]

    q2_constraint = results["q2"]["constraint_analysis"]
    q2_beta = results["q2"]["beta_behavior"]

    precision_map = {item["order"]: item["precision"] for item in q1_bleu["precisions"]}

    greedy_sequence = " ".join(_to_tex_safe_token(token) for token in q1_decode["greedy"]["sequence"])
    beam_sequence = " ".join(_to_tex_safe_token(token) for token in q1_decode["beam"]["best_sequence"])

    lines = [
        "% This file is auto-generated by main.py",
        f"\\newcommand{{\\QOneSentenceOneIndices}}{{{q1_pad['padded'][0]}}}",
        f"\\newcommand{{\\QOneSentenceTwoIndices}}{{{q1_pad['padded'][1]}}}",
        f"\\newcommand{{\\QOneSentenceThreeIndices}}{{{q1_pad['padded'][2]}}}",
        f"\\newcommand{{\\QOneGreedySequence}}{{{greedy_sequence}}}",
        f"\\newcommand{{\\QOneGreedyProb}}{{{q1_decode['greedy']['probability']:.4f}}}",
        f"\\newcommand{{\\QOneBeamSequence}}{{{beam_sequence}}}",
        f"\\newcommand{{\\QOneBeamProb}}{{{q1_decode['beam']['best_probability']:.4f}}}",
        f"\\newcommand{{\\QOneBleuPone}}{{{precision_map[1]:.4f}}}",
        f"\\newcommand{{\\QOneBleuPtwo}}{{{precision_map[2]:.4f}}}",
        f"\\newcommand{{\\QOneBleuPthree}}{{{precision_map[3]:.4f}}}",
        f"\\newcommand{{\\QOneBleuPfour}}{{{precision_map[4]:.4f}}}",
        f"\\newcommand{{\\QOneBleuBP}}{{{q1_bleu['brevity_penalty']:.4f}}}",
        f"\\newcommand{{\\QOneBleuScore}}{{{q1_bleu['bleu']:.4f}}}",
        f"\\newcommand{{\\QTwoSymmetryDiff}}{{{q2_constraint['symmetry_max_abs_diff']:.6f}}}",
        f"\\newcommand{{\\QTwoArgmaxIndex}}{{{q2_beta['argmax_index']}}}"
    ]

    os.makedirs(os.path.dirname(macro_path), exist_ok = True)

    with open(macro_path, "w", encoding = "utf-8") as file_obj:
        file_obj.write("\n".join(lines) + "\n")
